version: "3"
services:
  jmx-exporter-broker:
    image: bitnami/jmx-exporter:0.20.0
    volumes:
      - ./exporter/exporter-brokers.yml:/opt/bitnami/jmx-exporter/exporter.yml
    command:
      - "5556"
      - exporter.yml
    ports:
      - 9999:5556
    networks:
      - monitoring
  jmx-exporter-controller:
    image: bitnami/jmx-exporter:0.20.0
    volumes:
      - ./exporter/exporter-controllers.yml:/opt/bitnami/jmx-exporter/exporter.yml
    command:
      - "5556"
      - exporter.yml
    ports:
      - 9998:5556
    networks:
      - monitoring
  prometheus:
    image: bitnami/prometheus:2.48.0
    volumes:
      - ./prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    ports:
      - 9099:9090
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:10.2.2
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    ports:
      - 3000:3000
    networks:
      - monitoring

networks:
  monitoring:
    external: true
