version: "3"
services:
  kafka-exporter:
    image: bitnami/kafka-exporter:1.7.0
    command:
      - "--kafka.server=broker-1:9092"
    ports:
      - 9308:9308
    networks:
      - monitoring
  prometheus:
    image: bitnami/prometheus:2.48.0
    volumes:
      - ./prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    ports:
      - 9099:9090
    networks:
      - monitoring

networks:
  monitoring:
    external: true
